### ISSUE TITLE
Module build failed: Error: Cannot find module 'eslint-config-xo-space/browser'

### ISSUE THREAD

**Issue by cliffasaurus** [allenmichael/box-javascript-sdk#19]
Could not run `npm run build`

I have node v8.0.0
```
user@user-System-Product-Name:~/Documents/box-javascript-sdk$ npm run build

> box-javascript-sdk@1.0.0 build /home/user/Documents/box-javascript-sdk
> webpack --config webpack.config.js

(node:12746) [ESLINT_LEGACY_ECMAFEATURES] DeprecationWarning: The 'ecmaFeatures' config file property is deprecated, and has no effect. (found in ".eslintrc")
Hash: e6726ed2541a7f5bb852
Version: webpack 3.12.0
Time: 559ms
        Asset     Size  Chunks             Chunk Names
BoxSdk.min.js  2.76 kB       0  [emitted]  main
   BoxSdk.map  9.01 kB       0  [emitted]  main
   [0] ./src/sdk.js 1.99 kB {0} [built] [failed] [1 error]

ERROR in ./src/sdk.js
Module build failed: Error: Cannot find module 'eslint-config-xo-space/browser'
Referenced from: /home/user/Documents/package.json
    at ModuleResolver.resolve (/home/user/Documents/box-javascript-sdk/node_modules/eslint/lib/util/module-resolver.js:72:19)
    at resolve (/home/user/Documents/box-javascript-sdk/node_modules/eslint/lib/config/config-file.js:484:28)
    at load (/home/user/Documents/box-javascript-sdk/node_modules/eslint/lib/config/config-file.js:556:26)
    at configExtends.reduceRight (/home/user/Documents/box-javascript-sdk/node_modules/eslint/lib/config/config-file.js:430:36)
    at Array.reduceRight (native)
    at applyExtends (/home/user/Documents/box-javascript-sdk/node_modules/eslint/lib/config/config-file.js:408:26)
    at loadFromDisk (/home/user/Documents/box-javascript-sdk/node_modules/eslint/lib/config/config-file.js:528:22)
    at Object.load (/home/user/Documents/box-javascript-sdk/node_modules/eslint/lib/config/config-file.js:564:20)
    at Config.getLocalConfigHierarchy (/home/user/Documents/box-javascript-sdk/node_modules/eslint/lib/config.js:227:44)
    at Config.getConfigHierarchy (/home/user/Documents/box-javascript-sdk/node_modules/eslint/lib/config.js:179:43)
    at Config.getConfigVector (/home/user/Documents/box-javascript-sdk/node_modules/eslint/lib/config.js:286:21)
    at Config.getConfig (/home/user/Documents/box-javascript-sdk/node_modules/eslint/lib/config.js:329:29)
    at processText (/home/user/Documents/box-javascript-sdk/node_modules/eslint/lib/cli-engine.js:163:33)
    at CLIEngine.executeOnText (/home/user/Documents/box-javascript-sdk/node_modules/eslint/lib/cli-engine.js:635:17)
    at lint (/home/user/Documents/box-javascript-sdk/node_modules/eslint-loader/index.js:26:20)
    at Object.module.exports (/home/user/Documents/box-javascript-sdk/node_modules/eslint-loader/index.js:125:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! box-javascript-sdk@1.0.0 build: `webpack --config webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the box-javascript-sdk@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
edited `.eslintrc` to remove Depracation error:
```
"parserOptions": {
        "ecmaFeatures": {
            "modules": true
        }
    },
```
I also tried to ```npm install --save-dev eslint-config-xo-space```
cause I thought it might be a missing dependency but there's a huge block of error which is mostly:
```392:1   error    Expected indentation of 8 spaces but found 16                                                                  indent```

**Comment by allenmichael** [comment]
I don't see any issues with running and I'm on Node.js v10. I've even run build in a completelty new environment after cloning the repo and running `npm install`. I deleted the line within `.eslintrc` causing `DeprecationWarning`.

If you need a build of the current JS library, you can find build files in the `/build` directory in the repo.
